### ISSUE TITLE
部分角色套裝或二件套建議

### ISSUE THREAD

**Issue by 2phite** [FungusOVO/artifact#10]
# 位置：artifact/src/ys/data/characterData.json > 角色名稱["build"]["set"]

## 建議修改二件套選項（增量）
考察舊有的 characterData.json，我認為新角色的套裝選項可以作出以下修改：

### Baizhu
二件套 "s:hpp" 與四件套"TenacityOfTheMillelith" 重疊，可以刪除其一

### Chevreuse and Xianyun
"SongOfDaysPast" 可以改為 "s:hb"

### Xianyun
"ViridescentVenerer" 應該改為 "s:anemoDB"

## 建議修改套裝或二件套選項（減量）
和上述建議**相反**，舊有的 characterData.json 包括太多不常用的套裝或二件套。
例如，大多數輔助角色的 "s:hpp" 可以改為 "TenacityOfTheMillelith"；風輔的 "s:anemoDB" 可以改為 "ViridescentVenerer"…
估計工作量較大，如果時間允許，可考慮刪除多餘的套裝或二件套選項。

## 建議新增套裝選項（部分個人常用角色）
**只針對部分我個人常用角色**，尤其是草反應陣容，或者新聖遺物套裝，作出以下建議：

### Barbara
新增 "GildedDreams"

### Fischl
新增 "GildedDreams" 及 "FlowerOfParadiseLost"（或 "s:em"）
新增 "GoldenTroupe"

### Noelle
新增 "MarechausseeHunter"

### HuTao
新增 "MarechausseeHunter"

### RaidenShogun
新增 "GildedDreams" 及 "FlowerOfParadiseLost"（或 "s:em"）

### YaeMiko
新增 "GildedDreams" 及 "FlowerOfParadiseLost"（或 "s:em"）
新增 "GoldenTroupe"

### Kirara
新增 "NoblesseOblige"

### KukiShinobu
新增 "GildedDreams" 及 "FlowerOfParadiseLost"（或 "s:em"）
新增 "GoldenTroupe"

### Lynette
新增 "NoblesseOblige"？

# 位置：artifact/src/ys/data/characterData.json > 角色名稱["presets"]

## 建議新增 presets 選項
部分 preset 選項已經過時，尤其是草反應陣容。
雖然前文不包括全部角色，若進行修訂時，或許也可以參考前文。

# 位置：artifact/src/ys/data/characterData.json > 角色名稱["build"]["main"]

## 建議新增或修改 main
補充上述意見，可以修改部分角色主詞條選項。例如：

### YaeMiko
新增 "em"

**Comment by FungusOVO** [comment]
因为之前增加了给角色配装的功能，原来的["build"]["set"]已经废弃了，针对新的["setList"]配装，根据数组内的套装数量在配装时搭配四件套或者二件套，在按角色计算适配概率时取值为所有在配装中存在的套装。根据最新的逻辑，以下每一条分别回复下

> # 位置：artifact/src/ys/data/characterData.json > 角色名稱["build"]["set"]
> ## 建議修改二件套選項（增量）
> 考察舊有的 characterData.json，我認為新角色的套裝選項可以作出以下修改：
> 
> ### Baizhu
> 二件套 "s:hpp" 與四件套"TenacityOfTheMillelith" 重疊，可以刪除其一

新的配装里千岩套已删除

> ### Chevreuse and Xianyun
> "SongOfDaysPast" 可以改為 "s:hb"

接受建议已添加治疗二件套套装

> ### Xianyun
> "ViridescentVenerer" 應該改為 "s:anemoDB"

风4和风2区别还是蛮大的，不考虑修改

> ## 建議修改套裝或二件套選項（減量）
> 和上述建議**相反**，舊有的 characterData.json 包括太多不常用的套裝或二件套。 例如，大多數輔助角色的 "s:hpp" 可以改為 "TenacityOfTheMillelith"；風輔的 "s:anemoDB" 可以改為 "ViridescentVenerer"… 估計工作量較大，如果時間允許，可考慮刪除多餘的套裝或二件套選項。

新版本已经更新过所有角色的配装，二件套套装和四件套套装现在可以区分开了

> ## 建議新增套裝選項（部分個人常用角色）
> **只針對部分我個人常用角色**，尤其是草反應陣容，或者新聖遺物套裝，作出以下建議：
> 
> ### Barbara
> 新增 "GildedDreams"

新配装已添加

> ### Fischl
> 新增 "GildedDreams" 及 "FlowerOfParadiseLost"（或 "s:em"） 新增 "GoldenTroupe"

新配装已添加

> ### Noelle
> 新增 "MarechausseeHunter"

接受建议已添加

> ### HuTao
> 新增 "MarechausseeHunter"

新配装已添加

> ### RaidenShogun
> 新增 "GildedDreams" 及 "FlowerOfParadiseLost"（或 "s:em"）

新配装已添加

> ### YaeMiko
> 新增 "GildedDreams" 及 "FlowerOfParadiseLost"（或 "s:em"） 新增 "GoldenTroupe"

新配装已添加

> ### Kirara
> 新增 "NoblesseOblige"

新配装已添加

> ### KukiShinobu
> 新增 "GildedDreams" 及 "FlowerOfParadiseLost"（或 "s:em"） 新增 "GoldenTroupe"

新配装已添加

> ### Lynette
> 新增 "NoblesseOblige"？

新配装已添加

> # 位置：artifact/src/ys/data/characterData.json > 角色名稱["presets"]
> ## 建議新增 presets 選項
> 部分 preset 選項已經過時，尤其是草反應陣容。 雖然前文不包括全部角色，若進行修訂時，或許也可以參考前文。

["presets"] 已经删除了，从加载这种预设改成了按角色配装的权重取值

> # 位置：artifact/src/ys/data/characterData.json > 角色名稱["build"]["main"]
> ## 建議新增或修改 main
> 補充上述意見，可以修改部分角色主詞條選項。例如：
> 
> ### YaeMiko
> 新增 "em"

接受建议已修改

**Comment by 2phite** [comment]
感謝大佬解答
