### ISSUE TITLE
佬，我HSR.json导进去咋显示error呀

### ISSUE THREAD

**Issue by hcy0317** [FungusOVO/artifact#14]
是我哪没搞对吗？
![image](https://github.com/user-attachments/assets/1c899bbf-7f47-4977-8078-d8f2154eedf8)
[hsr.json](https://github.com/user-attachments/files/16402527/hsr.json)

**Comment by FungusOVO** [comment]
一开始只做了支持从[https://github.com/IceDynamix/reliquary-archiver](url)导入的hsr格式，现在yas扫描的也支持了

**Comment by wang-hui** [comment]
大佬您好，借地问一下，星铁有可以加解锁，类似于yas-lock的软件吗？

**Comment by FungusOVO** [comment]
> 大佬您好，借地问一下，星铁有可以加解锁，类似于yas-lock的软件吗？

星铁加解锁的yas-lock最近就会发布
